-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 21:55:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho_banco` ;
USE `trabalho_banco` ;

-- -----------------------------------------------------
-- Table `trabalho_banco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`usuario` (
  `cpf` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nasci` DATE NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`aluno` (
  `mat_aluno` VARCHAR(9) NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`mat_aluno`),
  INDEX `fk_estudante_usuario1_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_estudante_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `trabalho_banco`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`professor` (
  `mat_professor` VARCHAR(9) NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`mat_professor`),
  INDEX `fk_estudante_usuario1_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_estudante_usuario10`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `trabalho_banco`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`instrumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`instrumentos` (
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`, `tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`toca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`toca` (
  `nivel` INT NOT NULL,
  `instrumentos_nome` VARCHAR(45) NOT NULL,
  `instrumentos_tipo` VARCHAR(45) NOT NULL,
  `aluno_mat_aluno` VARCHAR(9) NOT NULL,
  INDEX `fk_toca_instrumentos1_idx` (`instrumentos_nome` ASC, `instrumentos_tipo` ASC) VISIBLE,
  INDEX `fk_toca_aluno1_idx` (`aluno_mat_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_toca_instrumentos1`
    FOREIGN KEY (`instrumentos_nome` , `instrumentos_tipo`)
    REFERENCES `trabalho_banco`.`instrumentos` (`nome` , `tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_toca_aluno1`
    FOREIGN KEY (`aluno_mat_aluno`)
    REFERENCES `trabalho_banco`.`aluno` (`mat_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`modulo` (
  `cod_modulo` VARCHAR(5) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`cod_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`leciona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`leciona` (
  `professor_mat_professor` INT NOT NULL,
  `instrumentos_nome` VARCHAR(45) NOT NULL,
  `instrumentos_tipo` VARCHAR(45) NOT NULL,
  `modulo_cod_modulo` VARCHAR(5) NOT NULL,
  INDEX `fk_leciona_professor1_idx` (`professor_mat_professor` ASC) VISIBLE,
  INDEX `fk_leciona_instrumentos1_idx` (`instrumentos_nome` ASC, `instrumentos_tipo` ASC) VISIBLE,
  INDEX `fk_leciona_modulo1_idx` (`modulo_cod_modulo` ASC) VISIBLE,
  CONSTRAINT `fk_leciona_professor1`
    FOREIGN KEY (`professor_mat_professor`)
    REFERENCES `trabalho_banco`.`professor` (`mat_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leciona_instrumentos1`
    FOREIGN KEY (`instrumentos_nome` , `instrumentos_tipo`)
    REFERENCES `trabalho_banco`.`instrumentos` (`nome` , `tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leciona_modulo1`
    FOREIGN KEY (`modulo_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`pagamento` (
  `id_compra` VARCHAR(45) NOT NULL,
  `flag` TINYINT(1) NOT NULL,
  `aluno_mat_aluno` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_pagamento_aluno1_idx` (`aluno_mat_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_aluno1`
    FOREIGN KEY (`aluno_mat_aluno`)
    REFERENCES `trabalho_banco`.`aluno` (`mat_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`cursa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`cursa` (
  `cursa_cod_modulo` VARCHAR(5) NOT NULL,
  `pagamento_id_compra` VARCHAR(45) NOT NULL,
  INDEX `fk_cursa_cursa1_idx` (`cursa_cod_modulo` ASC) VISIBLE,
  INDEX `fk_cursa_pagamento1_idx` (`pagamento_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_cursa_cursa1`
    FOREIGN KEY (`cursa_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursa_pagamento1`
    FOREIGN KEY (`pagamento_id_compra`)
    REFERENCES `trabalho_banco`.`pagamento` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`tecnico` (
  `nivel` INT NOT NULL,
  `video` BLOB NOT NULL,
  `parti_tabla` BLOB NOT NULL,
  `modulo_cod_modulo` VARCHAR(5) NOT NULL,
  INDEX `fk_tecnico_modulo1_idx` (`modulo_cod_modulo` ASC) VISIBLE,
  CONSTRAINT `fk_tecnico_modulo1`
    FOREIGN KEY (`modulo_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`modulos_adqu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`modulos_adqu` (
  `nome_modulo` VARCHAR(45) NOT NULL,
  `data_compra` DATE NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `pagamento_id_compra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pagamento_id_compra`),
  CONSTRAINT `fk_modulos_adqu_pagamento1`
    FOREIGN KEY (`pagamento_id_compra`)
    REFERENCES `trabalho_banco`.`pagamento` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`teorico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`teorico` (
  `horas` INT NOT NULL,
  `video` BLOB NOT NULL,
  `arquivos` BLOB NOT NULL,
  `modulo_cod_modulo` VARCHAR(5) NOT NULL,
  CONSTRAINT `fk_teorico_modulo1`
    FOREIGN KEY (`modulo_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `trabalho_banco` ;

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`customer_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`customer_list` (`ID` INT, `name` INT, `address` INT, `zip code` INT, `phone` INT, `city` INT, `country` INT, `notes` INT, `SID` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`film_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`film_list` (`FID` INT, `title` INT, `description` INT, `category` INT, `price` INT, `length` INT, `rating` INT, `actors` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`nicer_but_slower_film_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`nicer_but_slower_film_list` (`FID` INT, `title` INT, `description` INT, `category` INT, `price` INT, `length` INT, `rating` INT, `actors` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`staff_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`staff_list` (`ID` INT, `name` INT, `address` INT, `zip code` INT, `phone` INT, `city` INT, `country` INT, `SID` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`sales_by_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`sales_by_store` (`store` INT, `manager` INT, `total_sales` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`sales_by_film_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`sales_by_film_category` (`category` INT, `total_sales` INT);

-- -----------------------------------------------------
-- Placeholder table for view `trabalho_banco`.`actor_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`actor_info` (`actor_id` INT, `first_name` INT, `last_name` INT, `film_info` INT);

-- -----------------------------------------------------
-- procedure rewards_report
-- -----------------------------------------------------

DELIMITER $$
USE `trabalho_banco`$$


CREATE PROCEDURE `trabalho_banco`.`rewards_report` (
    IN min_monthly_purchases TINYINT UNSIGNED
    , IN min_dollar_amount_purchased DECIMAL(10,2) UNSIGNED
    , OUT count_rewardees INT
)
LANGUAGE SQL
NOT DETERMINISTIC 
READS SQL DATA
SQL SECURITY DEFINER
COMMENT 'Provides a customizable report on best customers'
proc: BEGIN
    
    DECLARE last_month_start DATE;
    DECLARE last_month_end DATE;

    /* Some sanity checks... */
    IF min_monthly_purchases = 0 THEN
        SELECT 'Minimum monthly purchases parameter must be > 0';
        LEAVE proc;
    END IF;
    IF min_dollar_amount_purchased = 0.00 THEN
        SELECT 'Minimum monthly dollar amount purchased parameter must be > $0.00';
        LEAVE proc;
    END IF;

    /* Determine start and end time periods */
    SET last_month_start = DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH);
    SET last_month_start = STR_TO_DATE(CONCAT(YEAR(last_month_start),'-',MONTH(last_month_start),'-01'),'%Y-%m-%d');
    SET last_month_end = LAST_DAY(last_month_start);

    /* 
        Create a temporary storage area for 
        Customer IDs.  
    */
    CREATE TEMPORARY TABLE tmpCustomer (customer_id SMALLINT UNSIGNED NOT NULL PRIMARY KEY);

    /* 
        Find all customers meeting the 
        monthly purchase requirements
    */
    INSERT INTO tmpCustomer (customer_id)
    SELECT p.customer_id 
    FROM payment AS p
    WHERE DATE(p.payment_date) BETWEEN last_month_start AND last_month_end
    GROUP BY customer_id
    HAVING SUM(p.amount) > min_dollar_amount_purchased
    AND COUNT(customer_id) > min_monthly_purchases;

    /* Populate OUT parameter with count of found customers */
    SELECT COUNT(*) FROM tmpCustomer INTO count_rewardees;

    /* 
        Output ALL customer information of matching rewardees.
        Customize output as needed.
    */
    SELECT c.* 
    FROM tmpCustomer AS t   
    INNER JOIN customer AS c ON t.customer_id = c.customer_id;

    /* Clean up */
    DROP TABLE tmpCustomer;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_customer_balance
-- -----------------------------------------------------

DELIMITER $$
USE `trabalho_banco`$$


CREATE FUNCTION `trabalho_banco`.`get_customer_balance`(p_customer_id INT, p_effective_date DATETIME) RETURNS DECIMAL(5,2)
    DETERMINISTIC
    READS SQL DATA
BEGIN

       #OK, WE NEED TO CALCULATE THE CURRENT BALANCE GIVEN A CUSTOMER_ID AND A DATE
       #THAT WE WANT THE BALANCE TO BE EFFECTIVE FOR. THE BALANCE IS:
       #   1) RENTAL FEES FOR ALL PREVIOUS RENTALS
       #   2) ONE DOLLAR FOR EVERY DAY THE PREVIOUS RENTALS ARE OVERDUE
       #   3) IF A FILM IS MORE THAN RENTAL_DURATION * 2 OVERDUE, CHARGE THE REPLACEMENT_COST
       #   4) SUBTRACT ALL PAYMENTS MADE BEFORE THE DATE SPECIFIED

  DECLARE v_rentfees DECIMAL(5,2); #FEES PAID TO RENT THE VIDEOS INITIALLY
  DECLARE v_overfees INTEGER;      #LATE FEES FOR PRIOR RENTALS
  DECLARE v_payments DECIMAL(5,2); #SUM OF PAYMENTS MADE PREVIOUSLY

  SELECT IFNULL(SUM(film.rental_rate),0) INTO v_rentfees
    FROM film, inventory, rental
    WHERE film.film_id = inventory.film_id
      AND inventory.inventory_id = rental.inventory_id
      AND rental.rental_date <= p_effective_date
      AND rental.customer_id = p_customer_id;

  SELECT IFNULL(SUM(IF((TO_DAYS(rental.return_date) - TO_DAYS(rental.rental_date)) > film.rental_duration,
        ((TO_DAYS(rental.return_date) - TO_DAYS(rental.rental_date)) - film.rental_duration),0)),0) INTO v_overfees
    FROM rental, inventory, film
    WHERE film.film_id = inventory.film_id
      AND inventory.inventory_id = rental.inventory_id
      AND rental.rental_date <= p_effective_date
      AND rental.customer_id = p_customer_id;


  SELECT IFNULL(SUM(payment.amount),0) INTO v_payments
    FROM payment

    WHERE payment.payment_date <= p_effective_date
    AND payment.customer_id = p_customer_id;

  RETURN v_rentfees + v_overfees - v_payments;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure film_in_stock
-- -----------------------------------------------------

DELIMITER $$
USE `trabalho_banco`$$


CREATE PROCEDURE `trabalho_banco`.`film_in_stock`(IN p_film_id INT, IN p_store_id INT, OUT p_film_count INT)
READS SQL DATA
BEGIN
     SELECT inventory_id
     FROM inventory
     WHERE film_id = p_film_id
     AND store_id = p_store_id
     AND inventory_in_stock(inventory_id);

     SELECT FOUND_ROWS() INTO p_film_count;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure film_not_in_stock
-- -----------------------------------------------------

DELIMITER $$
USE `trabalho_banco`$$


CREATE PROCEDURE `trabalho_banco`.`film_not_in_stock`(IN p_film_id INT, IN p_store_id INT, OUT p_film_count INT)
READS SQL DATA
BEGIN
     SELECT inventory_id
     FROM inventory
     WHERE film_id = p_film_id
     AND store_id = p_store_id
     AND NOT inventory_in_stock(inventory_id);

     SELECT FOUND_ROWS() INTO p_film_count;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function inventory_held_by_customer
-- -----------------------------------------------------

DELIMITER $$
USE `trabalho_banco`$$


CREATE FUNCTION `trabalho_banco`.`inventory_held_by_customer`(p_inventory_id INT) RETURNS INT
READS SQL DATA
BEGIN
  DECLARE v_customer_id INT;
  DECLARE EXIT HANDLER FOR NOT FOUND RETURN NULL;

  SELECT customer_id INTO v_customer_id
  FROM rental
  WHERE return_date IS NULL
  AND inventory_id = p_inventory_id;

  RETURN v_customer_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function inventory_in_stock
-- -----------------------------------------------------

DELIMITER $$
USE `trabalho_banco`$$


CREATE FUNCTION `trabalho_banco`.`inventory_in_stock`(p_inventory_id INT) RETURNS BOOLEAN
READS SQL DATA
BEGIN
    DECLARE v_rentals INT;
    DECLARE v_out     INT;

    #AN ITEM IS IN-STOCK IF THERE ARE EITHER NO ROWS IN THE rental TABLE
    #FOR THE ITEM OR ALL ROWS HAVE return_date POPULATED

    SELECT COUNT(*) INTO v_rentals
    FROM rental
    WHERE inventory_id = p_inventory_id;

    IF v_rentals = 0 THEN
      RETURN TRUE;
    END IF;

    SELECT COUNT(rental_id) INTO v_out
    FROM inventory LEFT JOIN rental USING(inventory_id)
    WHERE inventory.inventory_id = p_inventory_id
    AND rental.return_date IS NULL;

    IF v_out > 0 THEN
      RETURN FALSE;
    ELSE
      RETURN TRUE;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `trabalho_banco`.`customer_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`customer_list`;
USE `trabalho_banco`;
--
-- View structure for view `customer_list`
--

CREATE  OR REPLACE VIEW customer_list 
AS 
SELECT cu.customer_id AS ID, CONCAT(cu.first_name, _utf8' ', cu.last_name) AS name, a.address AS address, a.postal_code AS `zip code`,
	a.phone AS phone, city.city AS city, country.country AS country, IF(cu.active, _utf8'active',_utf8'') AS notes, cu.store_id AS SID 
FROM customer AS cu JOIN address AS a ON cu.address_id = a.address_id JOIN city ON a.city_id = city.city_id 
	JOIN country ON city.country_id = country.country_id;

-- -----------------------------------------------------
-- View `trabalho_banco`.`film_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`film_list`;
USE `trabalho_banco`;
--
-- View structure for view `film_list`
--

CREATE  OR REPLACE VIEW film_list 
AS 
SELECT film.film_id AS FID, film.title AS title, film.description AS description, category.name AS category, film.rental_rate AS price,
	film.length AS length, film.rating AS rating, GROUP_CONCAT(CONCAT(actor.first_name, _utf8' ', actor.last_name) SEPARATOR ', ') AS actors 
FROM category LEFT JOIN film_category ON category.category_id = film_category.category_id LEFT JOIN film ON film_category.film_id = film.film_id
        JOIN film_actor ON film.film_id = film_actor.film_id 
	JOIN actor ON film_actor.actor_id = actor.actor_id 
GROUP BY film.film_id, category.name;

-- -----------------------------------------------------
-- View `trabalho_banco`.`nicer_but_slower_film_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`nicer_but_slower_film_list`;
USE `trabalho_banco`;
--
-- View structure for view `nicer_but_slower_film_list`
--

CREATE  OR REPLACE VIEW nicer_but_slower_film_list 
AS 
SELECT film.film_id AS FID, film.title AS title, film.description AS description, category.name AS category, film.rental_rate AS price, 
	film.length AS length, film.rating AS rating, GROUP_CONCAT(CONCAT(CONCAT(UCASE(SUBSTR(actor.first_name,1,1)),
	LCASE(SUBSTR(actor.first_name,2,LENGTH(actor.first_name))),_utf8' ',CONCAT(UCASE(SUBSTR(actor.last_name,1,1)),
	LCASE(SUBSTR(actor.last_name,2,LENGTH(actor.last_name)))))) SEPARATOR ', ') AS actors 
FROM category LEFT JOIN film_category ON category.category_id = film_category.category_id LEFT JOIN film ON film_category.film_id = film.film_id
        JOIN film_actor ON film.film_id = film_actor.film_id
	JOIN actor ON film_actor.actor_id = actor.actor_id 
GROUP BY film.film_id, category.name;

-- -----------------------------------------------------
-- View `trabalho_banco`.`staff_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`staff_list`;
USE `trabalho_banco`;
--
-- View structure for view `staff_list`
--

CREATE  OR REPLACE VIEW staff_list 
AS 
SELECT s.staff_id AS ID, CONCAT(s.first_name, _utf8' ', s.last_name) AS name, a.address AS address, a.postal_code AS `zip code`, a.phone AS phone,
	city.city AS city, country.country AS country, s.store_id AS SID 
FROM staff AS s JOIN address AS a ON s.address_id = a.address_id JOIN city ON a.city_id = city.city_id 
	JOIN country ON city.country_id = country.country_id;

-- -----------------------------------------------------
-- View `trabalho_banco`.`sales_by_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`sales_by_store`;
USE `trabalho_banco`;
--
-- View structure for view `sales_by_store`
--

CREATE  OR REPLACE VIEW sales_by_store
AS 
SELECT 
CONCAT(c.city, _utf8',', cy.country) AS store
, CONCAT(m.first_name, _utf8' ', m.last_name) AS manager
, SUM(p.amount) AS total_sales
FROM payment AS p
INNER JOIN rental AS r ON p.rental_id = r.rental_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN store AS s ON i.store_id = s.store_id
INNER JOIN address AS a ON s.address_id = a.address_id
INNER JOIN city AS c ON a.city_id = c.city_id
INNER JOIN country AS cy ON c.country_id = cy.country_id
INNER JOIN staff AS m ON s.manager_staff_id = m.staff_id
GROUP BY s.store_id
ORDER BY cy.country, c.city;

-- -----------------------------------------------------
-- View `trabalho_banco`.`sales_by_film_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`sales_by_film_category`;
USE `trabalho_banco`;
--
-- View structure for view `sales_by_film_category`
--
-- Note that total sales will add up to >100% because
-- some titles belong to more than 1 category
--

CREATE  OR REPLACE VIEW sales_by_film_category
AS 
SELECT 
c.name AS category
, SUM(p.amount) AS total_sales
FROM payment AS p
INNER JOIN rental AS r ON p.rental_id = r.rental_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN film AS f ON i.film_id = f.film_id
INNER JOIN film_category AS fc ON f.film_id = fc.film_id
INNER JOIN category AS c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY total_sales DESC;

-- -----------------------------------------------------
-- View `trabalho_banco`.`actor_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho_banco`.`actor_info`;
USE `trabalho_banco`;
--
-- View structure for view `actor_info`
--

CREATE  OR REPLACE DEFINER=CURRENT_USER SQL SECURITY INVOKER VIEW actor_info 
AS
SELECT      
a.actor_id,
a.first_name,
a.last_name,
GROUP_CONCAT(DISTINCT CONCAT(c.name, ': ',
		(SELECT GROUP_CONCAT(f.title ORDER BY f.title SEPARATOR ', ')
                    FROM trabalho_banco.film f
                    INNER JOIN trabalho_banco.film_category fc
                      ON f.film_id = fc.film_id
                    INNER JOIN trabalho_banco.film_actor fa
                      ON f.film_id = fa.film_id
                    WHERE fc.category_id = c.category_id
                    AND fa.actor_id = a.actor_id
                 )
             )
             ORDER BY c.name SEPARATOR '; ')
AS film_info
FROM trabalho_banco.actor a
LEFT JOIN trabalho_banco.film_actor fa
  ON a.actor_id = fa.actor_id
LEFT JOIN trabalho_banco.film_category fc
  ON fa.film_id = fc.film_id
LEFT JOIN trabalho_banco.category c
  ON fc.category_id = c.category_id
GROUP BY a.actor_id, a.first_name, a.last_name;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
