-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 22:21:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho_banco` ;
USE `trabalho_banco` ;

-- -----------------------------------------------------
-- Table `trabalho_banco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`usuario` (
  `cpf` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nasci` DATE NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`aluno` (
  `mat_aluno` VARCHAR(9) NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`mat_aluno`),
  INDEX `fk_estudante_usuario1_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_estudante_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `trabalho_banco`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`professor` (
  `mat_professor` VARCHAR(9) NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`mat_professor`),
  INDEX `fk_estudante_usuario1_idx` (`usuario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_estudante_usuario10`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `trabalho_banco`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`instrumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`instrumentos` (
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`, `tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`toca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`toca` (
  `nivel` INT NOT NULL,
  `instrumentos_nome` VARCHAR(45) NOT NULL,
  `instrumentos_tipo` VARCHAR(45) NOT NULL,
  `aluno_mat_aluno` VARCHAR(9) NOT NULL,
  INDEX `fk_toca_instrumentos1_idx` (`instrumentos_nome` ASC, `instrumentos_tipo` ASC) VISIBLE,
  INDEX `fk_toca_aluno1_idx` (`aluno_mat_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_toca_instrumentos1`
    FOREIGN KEY (`instrumentos_nome` , `instrumentos_tipo`)
    REFERENCES `trabalho_banco`.`instrumentos` (`nome` , `tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_toca_aluno1`
    FOREIGN KEY (`aluno_mat_aluno`)
    REFERENCES `trabalho_banco`.`aluno` (`mat_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`modulo` (
  `cod_modulo` VARCHAR(5) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`cod_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`leciona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`leciona` (
  `professor_mat_professor` INT NOT NULL,
  `instrumentos_nome` VARCHAR(45) NOT NULL,
  `instrumentos_tipo` VARCHAR(45) NOT NULL,
  `modulo_cod_modulo` VARCHAR(5) NOT NULL,
  INDEX `fk_leciona_professor1_idx` (`professor_mat_professor` ASC) VISIBLE,
  INDEX `fk_leciona_instrumentos1_idx` (`instrumentos_nome` ASC, `instrumentos_tipo` ASC) VISIBLE,
  INDEX `fk_leciona_modulo1_idx` (`modulo_cod_modulo` ASC) VISIBLE,
  CONSTRAINT `fk_leciona_professor1`
    FOREIGN KEY (`professor_mat_professor`)
    REFERENCES `trabalho_banco`.`professor` (`mat_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leciona_instrumentos1`
    FOREIGN KEY (`instrumentos_nome` , `instrumentos_tipo`)
    REFERENCES `trabalho_banco`.`instrumentos` (`nome` , `tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leciona_modulo1`
    FOREIGN KEY (`modulo_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`pagamento` (
  `id_compra` VARCHAR(45) NOT NULL,
  `flag` TINYINT(1) NOT NULL,
  `aluno_mat_aluno` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_pagamento_aluno1_idx` (`aluno_mat_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_aluno1`
    FOREIGN KEY (`aluno_mat_aluno`)
    REFERENCES `trabalho_banco`.`aluno` (`mat_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`cursa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`cursa` (
  `cursa_cod_modulo` VARCHAR(5) NOT NULL,
  `pagamento_id_compra` VARCHAR(45) NOT NULL,
  INDEX `fk_cursa_cursa1_idx` (`cursa_cod_modulo` ASC) VISIBLE,
  INDEX `fk_cursa_pagamento1_idx` (`pagamento_id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_cursa_cursa1`
    FOREIGN KEY (`cursa_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursa_pagamento1`
    FOREIGN KEY (`pagamento_id_compra`)
    REFERENCES `trabalho_banco`.`pagamento` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`tecnico` (
  `nivel` INT NOT NULL,
  `video` BLOB NOT NULL,
  `parti_tabla` BLOB NOT NULL,
  `modulo_cod_modulo` VARCHAR(5) NOT NULL,
  INDEX `fk_tecnico_modulo1_idx` (`modulo_cod_modulo` ASC) VISIBLE,
  CONSTRAINT `fk_tecnico_modulo1`
    FOREIGN KEY (`modulo_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`modulos_adqu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`modulos_adqu` (
  `nome_modulo` VARCHAR(45) NOT NULL,
  `data_compra` DATE NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `pagamento_id_compra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pagamento_id_compra`),
  CONSTRAINT `fk_modulos_adqu_pagamento1`
    FOREIGN KEY (`pagamento_id_compra`)
    REFERENCES `trabalho_banco`.`pagamento` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_banco`.`teorico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_banco`.`teorico` (
  `horas` INT NOT NULL,
  `video` BLOB NOT NULL,
  `arquivos` BLOB NOT NULL,
  `modulo_cod_modulo` VARCHAR(5) NOT NULL,
  CONSTRAINT `fk_teorico_modulo1`
    FOREIGN KEY (`modulo_cod_modulo`)
    REFERENCES `trabalho_banco`.`modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
